sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t ovidiuvlad09/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true ovidiuvlad09/react-test npm test -- --coverage
after_success:
  - docker build -t ovidiuvlad09/multi-client ./client
  - docker build -t ovidiuvlad09/multi-nginx ./nginx
  - docker build -t ovidiuvlad09/multi-server ./server
  - docker build -t ovidiuvlad09/multi-worker ./worker
  # imagini ce le punem pe docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # imagini ce le luam si pe da PUSH pe DOCKER HUB
  - docker push ovidiuvlad09/multi-client
  - docker push ovidiuvlad09/multi-nginx
  - docker push ovidiuvlad09/multi-server
  - docker push ovidiuvlad09/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-343813294505'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
